#상품 목록

products = [
    {"id": 1, "category": "상의", "name": "투톤 반팔 셔츠", "season": ["여름"], "price": 15000},
    {"id": 2, "category": "상의", "name": "카라 화이트 블라우스", "season": ["봄", "가을"], "price": 25000},
    {"id": 3, "category": "상의", "name": "캐릭터 티셔츠", "season": ["가을", "겨울"], "price": 35000},
    {"id": 4, "category": "상의", "name": "라운드넥 심플 블랙 티셔츠", "season": ["가을", "겨울"], "price": 45000},
    {"id": 5, "category": "상의", "name": "브이넥 민소매 반팔", "season": ["여름"], "price": 30000},
    {"id": 6, "category": "상의", "name": "긴소매 크롭 탑", "season": ["봄", "가을"], "price": 15000},
    {"id": 7, "category": "상의", "name": "긴팔 스트라이프 블루 셔츠", "season": ["봄", "가을"], "price": 25000},
    {"id": 8, "category": "상의", "name": "심플 긴팔 니트", "season": ["가을", "겨울"], "price": 35000},
    {"id": 9, "category": "상의", "name": "기모 맨투맨", "season": ["가을", "겨울"], "price": 45000},
    {"id": 10, "category": "상의",  "name": "기모 없는 후드티", "season": ["봄", "가을"], "price": 30000},
    {"id": 11, "category" : "하의", "name": "미들 웨이스트 플리츠 치마바지", "season": ["봄", "가을"], "price": 40000},
    {"id": 12, "category" : "하의", "name": "데님 롱스커트", "season": ["봄", "가을"], "price": 35000},
    {"id": 13, "category" : "하의", "name": "흰 반바지", "season": ["여름"], "price": 25000},
    {"id": 14, "category" : "하의", "name": "긴 청바지", "season": ["겨울"], "price": 30000},
    {"id": 15, "category" : "하의", "name": "짧은 청바지", "season": ["여름"], "price": 20000},
    {"id": 16, "category" : "하의", "name": "플로럴 레이어드 맥시 스커트", "season": ["봄", "가을"], "price": 40000},
    {"id": 17, "category" : "하의", "name": "카고 조거 팬츠", "season": ["봄", "가을"], "price": 35000},
    {"id": 18, "category" : "하의", "name": "블랙 카고 반바지", "season": ["여름"], "price": 25000},
    {"id": 19, "category" : "하의", "name": "와이드 레그 팬츠", "season": ["겨울"], "price": 30000},
    {"id": 20, "category" : "하의", "name": "찢어진 스트레이트 레그 진", "season": ["여름"], "price": 20000},
    {"id": 21, "category" : "아우터", "name": "남색 바람막이", "season": ["봄", "가을"], "price": 55000},
    {"id": 22, "category" : "아우터", "name": "레더 지퍼 자켓", "season": ["겨울"], "price": 70000},
    {"id": 23, "category" : "아우터", "name": "아이보리 롱코드", "season": ["겨울"], "price": 80000},
    {"id": 24, "category" : "아우터", "name": "후드집업", "season": ["봄", "가을"], "price": 45000},
    {"id": 25, "category" : "아우터", "name": "숏패딩", "season": ["겨울"], "price": 60000},
    {"id": 26, "category" : "아우터", "name": "청자켓", "season": ["봄", "가을"], "price": 55000},
    {"id": 27, "category" : "아우터", "name": "롱패딩", "season": ["겨울"], "price": 70000},
    {"id": 28, "category" : "아우터", "name": "바이커 크롭 자켓", "season": ["겨울"], "price": 80000},
    {"id": 29, "category" : "아우터", "name": "조끼 패딩", "season": ["봄", "가을"], "price": 45000},
    {"id": 30, "category" : "아우터", "name": "떡볶이 코트", "season": ["겨울"], "price": 60000},
]