#상품 목록

products = [
    {"id": 1, "main-category": "상의", "name": "A", "category": "티셔츠", "season": ["봄", "가을"], "price": 15000},
    {"id": 2, "main-category": "상의", "name": "B", "category": "셔츠", "season": ["봄", "가을"], "price": 25000},
    {"id": 3, "main-category": "상의", "name": "C", "category": "후드티", "season": ["가을", "겨울"], "price": 35000},
    {"id": 4, "main-category": "상의", "name": "D", "category": "니트", "season": ["가을", "겨울"], "price": 45000},
    {"id": 5, "main-category": "상의", "name": "E", "category": "맨투맨", "season": ["봄", "가을"], "price": 30000},
    {"id": 6, "main-category": "상의", "name": "A1", "category": "티셔츠", "season": ["봄", "가을"], "price": 15000},
    {"id": 7, "main-category": "상의", "name": "B1", "category": "셔츠", "season": ["봄", "가을"], "price": 25000},
    {"id": 8, "main-category": "상의", "name": "C1", "category": "후드티", "season": ["가을", "겨울"], "price": 35000},
    {"id": 9, "main-category": "상의", "name": "D1", "category": "니트", "season": ["가을", "겨울"], "price": 45000},
    {"id": 10, "main-category": "상의",  "name": "E1", "category": "맨투맨", "season": ["봄", "가을"], "price": 30000},
    {"id": 11, "main-category" : "하의", "name": "F", "category": "청바지", "season": ["봄", "가을"], "price": 40000},
    {"id": 12, "main-category" : "하의", "name": "G", "category": "슬랙스", "season": ["봄", "가을"], "price": 35000},
    {"id": 13, "main-category" : "하의", "name": "H", "category": "면바지", "season": ["여름"], "price": 25000},
    {"id": 14, "main-category" : "하의", "name": "I", "category": "트레이닝 바지", "season": ["겨울"], "price": 30000},
    {"id": 15, "main-category" : "하의", "name": "J", "category": "치마", "season": ["여름"], "price": 20000},
    {"id": 16, "main-category" : "하의", "name": "F1", "category": "청바지", "season": ["봄", "가을"], "price": 40000},
    {"id": 17, "main-category" : "하의", "name": "G1", "category": "슬랙스", "season": ["봄", "가을"], "price": 35000},
    {"id": 18, "main-category" : "하의", "name": "H1", "category": "면바지", "season": ["여름"], "price": 25000},
    {"id": 19, "main-category" : "하의", "name": "I1", "category": "트레이닝 바지", "season": ["겨울"], "price": 30000},
    {"id": 20, "main-category" : "하의", "name": "J1", "category": "치마", "season": ["여름"], "price": 20000},
    {"id": 21, "main-category" : "아우터", "name": "K", "category": "자켓", "season": ["봄", "가을"], "price": 55000},
    {"id": 22, "main-category" : "아우터", "name": "L", "category": "코트", "season": ["겨울"], "price": 70000},
    {"id": 23, "main-category" : "아우터", "name": "M", "category": "패딩", "season": ["겨울"], "price": 80000},
    {"id": 24, "main-category" : "아우터", "name": "N", "category": "가디건", "season": ["봄", "가을"], "price": 45000},
    {"id": 25, "main-category" : "아우터", "name": "O", "category": "점퍼", "season": ["겨울"], "price": 60000},
    {"id": 26, "main-category" : "아우터", "name": "K1", "category": "자켓", "season": ["봄", "가을"], "price": 55000},
    {"id": 27, "main-category" : "아우터", "name": "L1", "category": "코트", "season": ["겨울"], "price": 70000},
    {"id": 28, "main-category" : "아우터", "name": "M1", "category": "패딩", "season": ["겨울"], "price": 80000},
    {"id": 29, "main-category" : "아우터", "name": "N1", "category": "가디건", "season": ["봄", "가을"], "price": 45000},
    {"id": 30, "main-category" : "아우터", "name": "O1", "category": "점퍼", "season": ["겨울"], "price": 60000},
]