#상품 목록

products = [
    {"id": 1, "category": "상의", "name": "A", "season": ["봄", "가을"], "price": 15000},
    {"id": 2, "category": "상의", "name": "B", "season": ["봄", "가을"], "price": 25000},
    {"id": 3, "category": "상의", "name": "C", "season": ["가을", "겨울"], "price": 35000},
    {"id": 4, "category": "상의", "name": "D", "season": ["가을", "겨울"], "price": 45000},
    {"id": 5, "category": "상의", "name": "E", "season": ["봄", "가을"], "price": 30000},
    {"id": 6, "category": "상의", "name": "A1", "season": ["봄", "가을"], "price": 15000},
    {"id": 7, "category": "상의", "name": "B1", "season": ["봄", "가을"], "price": 25000},
    {"id": 8, "category": "상의", "name": "C1", "season": ["가을", "겨울"], "price": 35000},
    {"id": 9, "category": "상의", "name": "D1", "season": ["가을", "겨울"], "price": 45000},
    {"id": 10, "category": "상의",  "name": "E1", "season": ["봄", "가을"], "price": 30000},
    {"id": 11, "category" : "하의", "name": "F", "season": ["봄", "가을"], "price": 40000},
    {"id": 12, "category" : "하의", "name": "G", "season": ["봄", "가을"], "price": 35000},
    {"id": 13, "category" : "하의", "name": "H", "season": ["여름"], "price": 25000},
    {"id": 14, "category" : "하의", "name": "I", "season": ["겨울"], "price": 30000},
    {"id": 15, "category" : "하의", "name": "J", "season": ["여름"], "price": 20000},
    {"id": 16, "category" : "하의", "name": "F1", "season": ["봄", "가을"], "price": 40000},
    {"id": 17, "category" : "하의", "name": "G1", "season": ["봄", "가을"], "price": 35000},
    {"id": 18, "category" : "하의", "name": "H1", "season": ["여름"], "price": 25000},
    {"id": 19, "category" : "하의", "name": "I1", "season": ["겨울"], "price": 30000},
    {"id": 20, "category" : "하의", "name": "J1", "season": ["여름"], "price": 20000},
    {"id": 21, "category" : "아우터", "name": "K", "season": ["봄", "가을"], "price": 55000},
    {"id": 22, "category" : "아우터", "name": "L", "season": ["겨울"], "price": 70000},
    {"id": 23, "category" : "아우터", "name": "M", "season": ["겨울"], "price": 80000},
    {"id": 24, "category" : "아우터", "name": "N", "season": ["봄", "가을"], "price": 45000},
    {"id": 25, "category" : "아우터", "name": "O", "season": ["겨울"], "price": 60000},
    {"id": 26, "category" : "아우터", "name": "K1", "season": ["봄", "가을"], "price": 55000},
    {"id": 27, "category" : "아우터", "name": "L1", "season": ["겨울"], "price": 70000},
    {"id": 28, "category" : "아우터", "name": "M1", "season": ["겨울"], "price": 80000},
    {"id": 29, "category" : "아우터", "name": "N1", "season": ["봄", "가을"], "price": 45000},
    {"id": 30, "category" : "아우터", "name": "O1", "season": ["겨울"], "price": 60000},
]